EXTRACT_TABLE = {
    "name": "villager_name",
    "gender": "gender",
    "UUID": "uuid",
    "hearts": 'int(entity["memories"][0]["hearts"].value)',
    "mood": 'entity["mood"].value',
    "age_state": 'const.AGE_STATE[entity["ageState"].value]',
    "has_baby": "has_baby",
    "profession": "profession",
    "has_trading": "has_trading",
    "village_name": 'village_info[uuid]["village_name"]',
    "position(coordinate_x)": 'round(entity["Pos"][0].value)',
    "position(coordinate_y)": 'round(entity["Pos"][1].value)',
    "position(coordinate_z)": 'round(entity["Pos"][2].value)',
    "position(region_x)": "region_x",
    "position(region_z)": "region_z",
    "position(chunk_x)": "chunk_x",
    "position(chunk_z)": "chunk_z",
    "position(world_chunk_x)": "world_chunk_x",
    "position(world_chunk_z)": "world_chunk_z",
    "clothes": 'entity["clothes"].value',
    "hair": 'entity["hair"].value',
    "gene_eumelanin": 'entity["gene_eumelanin"].value',
    "gene_face": 'entity["gene_face"].value',
    "gene_hemoglobin": 'entity["gene_hemoglobin"].value',
    "gene_melanin": 'entity["gene_melanin"].value',
    "gene_pheomelanin": 'entity["gene_pheomelanin"].value',
    "gene_skin": 'entity["gene_skin"].value',
    "hair_color_blue": 'entity["hair_color_blue"].value',
    "hair_color_green": 'entity["hair_color_green"].value',
    "hair_color_red": 'entity["hair_color_red"].value',
    "albinism": "albinism",
    "hetero": "hetero",
    "updated": "True",
}

MAID_EXTRACT_TABLE = {
    "name": "name",
    "gender": '"女"',
    "UUID": "uuid",
    "hearts": "100",
    "mood": "15",
    "age_state": '"-"',
    "has_baby": "False",
    "profession": "profession",
    "has_trading": "False",
    "village_name": '"-"',
    "position(coordinate_x)": 'round(entity["Pos"][0].value)',
    "position(coordinate_y)": 'round(entity["Pos"][1].value)',
    "position(coordinate_z)": 'round(entity["Pos"][2].value)',
    "position(region_x)": "region_x",
    "position(region_z)": "region_z",
    "position(chunk_x)": "chunk_x",
    "position(chunk_z)": "chunk_z",
    "position(world_chunk_x)": "world_chunk_x",
    "position(world_chunk_z)": "world_chunk_z",
    "clothes": '"-"',
    "hair": '"-"',
    "gene_eumelanin": "0",
    "gene_face": "0",
    "gene_hemoglobin": "0",
    "gene_melanin": "0",
    "gene_pheomelanin": "0",
    "gene_skin": "0",
    "hair_color_blue": "0",
    "hair_color_green": "0",
    "hair_color_red": "0",
    "albinism": "0",
    "hetero": "False",
    "updated": "True",
}

VILLAGE_INFO_TABLE = {
    "village_name": "village_name",
    "left_top_x": "left_top.get_x()",
    "left_top_y": "left_top.get_y()",
    "left_top_z": "left_top.get_z()",
    "right_bottom_x": "right_bottom.get_x()",
    "right_bottom_y": "right_bottom.get_y()",
    "right_bottom_z": "right_bottom.get_z()",
    "center_x": "center.get_x()",
    "center_y": "center.get_y()",
    "center_z": "center.get_z()",
}

PROFESSION_TABLE = {
    "minecraft:none": "無職",
    "minecraft:farmer": "農民",
    "minecraft:fisherman": "釣り人",
    "minecraft:shepherd": "羊飼い",
    "minecraft:fletcher": "矢師",
    "minecraft:librarian": "司書",
    "minecraft:cartographer": "製図家",
    "minecraft:cleric": "聖職者",
    "minecraft:armorer": "防具鍛冶",
    "minecraft:weaponsmith": "武器鍛冶",
    "minecraft:toolsmith": "道具鍛冶",
    "minecraft:butcher": "肉屋",
    "minecraft:leatherworker": "革細工師",
    "minecraft:mason": "石工",
    "minecraft:nitwit": "ニート",
    "mca:none": "無職",
    "mca:outlaw": "無法者",
    "mca:jeweler": "宝石商",
    "mca:pillager": "略奪者",
    "mca:miner": "坑夫",
    "mca:baker": "パン屋",
    "mca:guard": "衛兵",
    "mca:warrior": "戦士",
    "mca:archer": "弓兵",
    "mca:adventurer": "冒険家",
    "mca:mercenary": "傭兵",
    "mca:cultist": "カルト信者",
    "mca:child": "子ども",
    "chefsdelight:delightcook": "料理人",
    "chefsdelight:delightchef": "シェフ",
    "morevillagers:oceanographer": "海洋学者",
    "morevillagers:netherian": "怪異学者",
    "morevillagers:woodworker": "林業家",
    "morevillagers:enderian": "エンド研究家",
    "morevillagers:engineer": "エンジニア",
    "morevillagers:florist": "花屋",
    "morevillagers:hunter": "猟師",
    "morevillagers:miner": "鉱夫",
    "villagersplus:alchemist": "錬金術師",
    "villagersplus:occultist": "オカルティスト",
    "villagersplus:oceanographer": "海洋学者",
    "villagersplus:horticulturist": "園芸家",
    "brewery:brewer": "醸造家",
    "blue_skies:stargazer": "天文学者",
    "the_beginning_and_heaven:jewelry_box": "宝石商",
}

AGE_STATE = {
    1: "赤ちゃん",
    2: "幼児",
    3: "子供",
    4: "思春期",
    5: "大人",
}

ATTR_TABLE = {
    "max_health": "attribute {} minecraft:generic.max_health base set 1024",
    "armor": "attribute {} minecraft:generic.armor base set 40",
    "follow_range": "attribute {} minecraft:generic.follow_range base set 96",
    "movement_speed": "attribute {} minecraft:generic.movement_speed base set ",
}

HEAL_COMMANDS = [
    "effect give @e[type=mca:male_villager] minecraft:instant_health 5 250 true",
    "effect give @e[type=mca:female_villager] minecraft:instant_health 5 250 true",
    "effect give @e[type=littlemaidrebirth:little_maid_mob] minecraft:instant_health 5 250 true",
    "effect give @e[type=touhou_little_maid:maid] minecraft:instant_health 5 250 true",
]

FACE_COUNT = 22
